# Data

## Time-Temperature

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>t</th>
      <th>T</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>80</td>
      <td>320</td>
    </tr>
    <tr>
      <th>1</th>
      <td>137</td>
      <td>340</td>
    </tr>
    <tr>
      <th>2</th>
      <td>204</td>
      <td>360</td>
    </tr>
    <tr>
      <th>3</th>
      <td>274</td>
      <td>380</td>
    </tr>
    <tr>
      <th>4</th>
      <td>355</td>
      <td>400</td>
    </tr>
  </tbody>
</table>

## Temperature-Intensity

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Temperature</th>
      <th>Intensity</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>305</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>310</td>
      <td>0.4</td>
    </tr>
    <tr>
      <th>2</th>
      <td>315</td>
      <td>1.2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>320</td>
      <td>2.2</td>
    </tr>
    <tr>
      <th>4</th>
      <td>325</td>
      <td>3.4</td>
    </tr>
    <tr>
      <th>5</th>
      <td>330</td>
      <td>4.6</td>
    </tr>
    <tr>
      <th>6</th>
      <td>335</td>
      <td>6.1</td>
    </tr>
    <tr>
      <th>7</th>
      <td>340</td>
      <td>7.6</td>
    </tr>
    <tr>
      <th>8</th>
      <td>345</td>
      <td>9.0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>350</td>
      <td>10.2</td>
    </tr>
    <tr>
      <th>10</th>
      <td>355</td>
      <td>11.1</td>
    </tr>
    <tr>
      <th>11</th>
      <td>360</td>
      <td>12.1</td>
    </tr>
    <tr>
      <th>12</th>
      <td>365</td>
      <td>13.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>370</td>
      <td>13.9</td>
    </tr>
    <tr>
      <th>14</th>
      <td>372</td>
      <td>14.0</td>
    </tr>
    <tr>
      <th>15</th>
      <td>375</td>
      <td>14.2</td>
    </tr>
    <tr>
      <th>16</th>
      <td>377</td>
      <td>14.3</td>
    </tr>
    <tr>
      <th>17</th>
      <td>380</td>
      <td>14.4</td>
    </tr>
    <tr>
      <th>18</th>
      <td>382</td>
      <td>14.2</td>
    </tr>
    <tr>
      <th>19</th>
      <td>383</td>
      <td>14.0</td>
    </tr>
    <tr>
      <th>20</th>
      <td>384</td>
      <td>13.8</td>
    </tr>
    <tr>
      <th>21</th>
      <td>385</td>
      <td>13.6</td>
    </tr>
    <tr>
      <th>22</th>
      <td>390</td>
      <td>12.1</td>
    </tr>
    <tr>
      <th>23</th>
      <td>395</td>
      <td>9.5</td>
    </tr>
    <tr>
      <th>24</th>
      <td>400</td>
      <td>6.4</td>
    </tr>
    <tr>
      <th>25</th>
      <td>405</td>
      <td>3.5</td>
    </tr>
    <tr>
      <th>26</th>
      <td>410</td>
      <td>1.7</td>
    </tr>
    <tr>
      <th>27</th>
      <td>415</td>
      <td>0.5</td>
    </tr>
    <tr>
      <th>28</th>
      <td>419</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>

# Plots

## Time-Temperature

![](T-t.jpg)

## Temperature-Intensity

![](T-I.jpg)