## Heating

### Data

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Temperature in Degrees Celcius</th>
      <th>Capacitance in pF</th>
      <th>Dielectric Constant</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>40</td>
      <td>405</td>
      <td>1160.46</td>
    </tr>
    <tr>
      <th>1</th>
      <td>45</td>
      <td>407</td>
      <td>1166.19</td>
    </tr>
    <tr>
      <th>2</th>
      <td>50</td>
      <td>409</td>
      <td>1171.92</td>
    </tr>
    <tr>
      <th>3</th>
      <td>55</td>
      <td>410</td>
      <td>1174.79</td>
    </tr>
    <tr>
      <th>4</th>
      <td>60</td>
      <td>414</td>
      <td>1186.25</td>
    </tr>
    <tr>
      <th>5</th>
      <td>65</td>
      <td>416</td>
      <td>1191.98</td>
    </tr>
    <tr>
      <th>6</th>
      <td>70</td>
      <td>420</td>
      <td>1203.44</td>
    </tr>
    <tr>
      <th>7</th>
      <td>75</td>
      <td>423</td>
      <td>1212.03</td>
    </tr>
    <tr>
      <th>8</th>
      <td>80</td>
      <td>428</td>
      <td>1226.36</td>
    </tr>
    <tr>
      <th>9</th>
      <td>85</td>
      <td>434</td>
      <td>1243.55</td>
    </tr>
    <tr>
      <th>10</th>
      <td>90</td>
      <td>440</td>
      <td>1260.74</td>
    </tr>
    <tr>
      <th>11</th>
      <td>95</td>
      <td>448</td>
      <td>1283.67</td>
    </tr>
    <tr>
      <th>12</th>
      <td>100</td>
      <td>459</td>
      <td>1315.19</td>
    </tr>
    <tr>
      <th>13</th>
      <td>105</td>
      <td>469</td>
      <td>1343.84</td>
    </tr>
    <tr>
      <th>14</th>
      <td>110</td>
      <td>484</td>
      <td>1386.82</td>
    </tr>
    <tr>
      <th>15</th>
      <td>115</td>
      <td>503</td>
      <td>1441.26</td>
    </tr>
    <tr>
      <th>16</th>
      <td>120</td>
      <td>529</td>
      <td>1515.76</td>
    </tr>
    <tr>
      <th>17</th>
      <td>125</td>
      <td>564</td>
      <td>1616.05</td>
    </tr>
    <tr>
      <th>18</th>
      <td>130</td>
      <td>594</td>
      <td>1702.01</td>
    </tr>
    <tr>
      <th>19</th>
      <td>135</td>
      <td>622</td>
      <td>1782.23</td>
    </tr>
    <tr>
      <th>20</th>
      <td>137</td>
      <td>628</td>
      <td>1799.43</td>
    </tr>
    <tr>
      <th>21</th>
      <td>140</td>
      <td>632</td>
      <td>1810.89</td>
    </tr>
    <tr>
      <th>22</th>
      <td>142</td>
      <td>625</td>
      <td>1790.83</td>
    </tr>
    <tr>
      <th>23</th>
      <td>145</td>
      <td>613</td>
      <td>1756.45</td>
    </tr>
    <tr>
      <th>24</th>
      <td>150</td>
      <td>583</td>
      <td>1670.49</td>
    </tr>
    <tr>
      <th>25</th>
      <td>155</td>
      <td>550</td>
      <td>1575.93</td>
    </tr>
    <tr>
      <th>26</th>
      <td>160</td>
      <td>518</td>
      <td>1484.24</td>
    </tr>
    <tr>
      <th>27</th>
      <td>165</td>
      <td>490</td>
      <td>1404.01</td>
    </tr>
    <tr>
      <th>28</th>
      <td>170</td>
      <td>464</td>
      <td>1329.51</td>
    </tr>
  </tbody>
</table>

### Plot

![](DC1I.jpg)

## Cooling

### Data

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Temperature in Degrees Celcius</th>
      <th>Capacitance in pF</th>
      <th>Dielectric Constant</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>40</td>
      <td>403</td>
      <td>1154.73</td>
    </tr>
    <tr>
      <th>1</th>
      <td>45</td>
      <td>405</td>
      <td>1160.46</td>
    </tr>
    <tr>
      <th>2</th>
      <td>50</td>
      <td>406</td>
      <td>1163.32</td>
    </tr>
    <tr>
      <th>3</th>
      <td>55</td>
      <td>408</td>
      <td>1169.05</td>
    </tr>
    <tr>
      <th>4</th>
      <td>60</td>
      <td>411</td>
      <td>1177.65</td>
    </tr>
    <tr>
      <th>5</th>
      <td>65</td>
      <td>414</td>
      <td>1186.25</td>
    </tr>
    <tr>
      <th>6</th>
      <td>70</td>
      <td>417</td>
      <td>1194.84</td>
    </tr>
    <tr>
      <th>7</th>
      <td>75</td>
      <td>421</td>
      <td>1206.30</td>
    </tr>
    <tr>
      <th>8</th>
      <td>80</td>
      <td>426</td>
      <td>1220.63</td>
    </tr>
    <tr>
      <th>9</th>
      <td>85</td>
      <td>430</td>
      <td>1232.09</td>
    </tr>
    <tr>
      <th>10</th>
      <td>90</td>
      <td>437</td>
      <td>1252.15</td>
    </tr>
    <tr>
      <th>11</th>
      <td>95</td>
      <td>446</td>
      <td>1277.94</td>
    </tr>
    <tr>
      <th>12</th>
      <td>100</td>
      <td>458</td>
      <td>1312.32</td>
    </tr>
    <tr>
      <th>13</th>
      <td>105</td>
      <td>469</td>
      <td>1343.84</td>
    </tr>
    <tr>
      <th>14</th>
      <td>110</td>
      <td>485</td>
      <td>1389.68</td>
    </tr>
    <tr>
      <th>15</th>
      <td>115</td>
      <td>502</td>
      <td>1438.40</td>
    </tr>
    <tr>
      <th>16</th>
      <td>120</td>
      <td>528</td>
      <td>1512.89</td>
    </tr>
    <tr>
      <th>17</th>
      <td>125</td>
      <td>563</td>
      <td>1613.18</td>
    </tr>
    <tr>
      <th>18</th>
      <td>130</td>
      <td>594</td>
      <td>1702.01</td>
    </tr>
    <tr>
      <th>19</th>
      <td>135</td>
      <td>620</td>
      <td>1776.50</td>
    </tr>
    <tr>
      <th>20</th>
      <td>137</td>
      <td>627</td>
      <td>1796.56</td>
    </tr>
    <tr>
      <th>21</th>
      <td>140</td>
      <td>630</td>
      <td>1805.16</td>
    </tr>
    <tr>
      <th>22</th>
      <td>142</td>
      <td>624</td>
      <td>1787.97</td>
    </tr>
    <tr>
      <th>23</th>
      <td>145</td>
      <td>613</td>
      <td>1756.45</td>
    </tr>
    <tr>
      <th>24</th>
      <td>150</td>
      <td>580</td>
      <td>1661.89</td>
    </tr>
    <tr>
      <th>25</th>
      <td>155</td>
      <td>547</td>
      <td>1567.34</td>
    </tr>
    <tr>
      <th>26</th>
      <td>160</td>
      <td>516</td>
      <td>1478.51</td>
    </tr>
    <tr>
      <th>27</th>
      <td>165</td>
      <td>488</td>
      <td>1398.28</td>
    </tr>
    <tr>
      <th>28</th>
      <td>170</td>
      <td>464</td>
      <td>1329.51</td>
    </tr>
  </tbody>
</table>

### Plot

![](DC2I.jpg)