## Part A

### Data

<table>
  <thead>
    <tr style="text-align: center;">
      <th></th>
      <th>Current (in mA)</th>
      <th>Voltage (in V)</th>
      <th>lnI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.1</td>
      <td>0.605</td>
      <td>-2.303</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.2</td>
      <td>0.634</td>
      <td>-1.609</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0.3</td>
      <td>0.651</td>
      <td>-1.204</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0.4</td>
      <td>0.662</td>
      <td>-0.916</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0.5</td>
      <td>0.670</td>
      <td>-0.693</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.7</td>
      <td>0.683</td>
      <td>-0.357</td>
    </tr>
    <tr>
      <th>6</th>
      <td>1.0</td>
      <td>0.697</td>
      <td>0.000</td>
    </tr>
    <tr>
      <th>7</th>
      <td>1.5</td>
      <td>0.711</td>
      <td>0.405</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2.0</td>
      <td>0.721</td>
      <td>0.693</td>
    </tr>
    <tr>
      <th>9</th>
      <td>3.0</td>
      <td>0.736</td>
      <td>1.099</td>
    </tr>
    <tr>
      <th>10</th>
      <td>4.0</td>
      <td>0.746</td>
      <td>1.386</td>
    </tr>
    <tr>
      <th>11</th>
      <td>5.0</td>
      <td>0.754</td>
      <td>1.609</td>
    </tr>
    <tr>
      <th>12</th>
      <td>7.0</td>
      <td>0.767</td>
      <td>1.946</td>
    </tr>
    <tr>
      <th>13</th>
      <td>10.0</td>
      <td>0.781</td>
      <td>2.303</td>
    </tr>
  </tbody>
</table>

### Plot

![](img_VI.jpg)

## Part B

### Data

<table>
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Temperature (in K)</th>
      <th>Voltage (in V)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>305</td>
      <td>0.694</td>
    </tr>
    <tr>
      <th>1</th>
      <td>310</td>
      <td>0.688</td>
    </tr>
    <tr>
      <th>2</th>
      <td>315</td>
      <td>0.678</td>
    </tr>
    <tr>
      <th>3</th>
      <td>320</td>
      <td>0.668</td>
    </tr>
    <tr>
      <th>4</th>
      <td>330</td>
      <td>0.645</td>
    </tr>
    <tr>
      <th>5</th>
      <td>340</td>
      <td>0.626</td>
    </tr>
    <tr>
      <th>6</th>
      <td>350</td>
      <td>0.610</td>
    </tr>
    <tr>
      <th>7</th>
      <td>355</td>
      <td>0.601</td>
    </tr>
    <tr>
      <th>8</th>
      <td>360</td>
      <td>0.593</td>
    </tr>
    <tr>
      <th>9</th>
      <td>365</td>
      <td>0.584</td>
    </tr>
    <tr>
      <th>10</th>
      <td>370</td>
      <td>0.576</td>
    </tr>
    <tr>
      <th>11</th>
      <td>375</td>
      <td>0.572</td>
    </tr>
  </tbody>
</table>

### Plot

![](img_TV.jpg)

## Part C

### Data

<table>
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Voltage (in V)</th>
      <th>Voltage at 5KHz (in V)</th>
      <th>Voltage at 20KHz (in V)</th>
      <th>Cd (in pF)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0.0</td>
      <td>84</td>
      <td>241</td>
      <td>92.614</td>
    </tr>
    <tr>
      <th>1</th>
      <td>-0.5</td>
      <td>62</td>
      <td>169</td>
      <td>64.459</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-1.0</td>
      <td>52</td>
      <td>143</td>
      <td>54.616</td>
    </tr>
    <tr>
      <th>3</th>
      <td>-2.0</td>
      <td>46</td>
      <td>115</td>
      <td>43.214</td>
    </tr>
    <tr>
      <th>4</th>
      <td>-3.0</td>
      <td>44</td>
      <td>101</td>
      <td>37.274</td>
    </tr>
    <tr>
      <th>5</th>
      <td>-4.0</td>
      <td>42</td>
      <td>94</td>
      <td>34.479</td>
    </tr>
    <tr>
      <th>6</th>
      <td>-5.0</td>
      <td>38</td>
      <td>85</td>
      <td>31.173</td>
    </tr>
    <tr>
      <th>7</th>
      <td>-7.0</td>
      <td>35</td>
      <td>78</td>
      <td>28.580</td>
    </tr>
    <tr>
      <th>8</th>
      <td>-9.0</td>
      <td>32</td>
      <td>72</td>
      <td>26.444</td>
    </tr>
    <tr>
      <th>9</th>
      <td>-10.0</td>
      <td>30</td>
      <td>68</td>
      <td>25.020</td>
    </tr>
    <tr>
      <th>10</th>
      <td>-11.5</td>
      <td>28</td>
      <td>65</td>
      <td>24.051</td>
    </tr>
  </tbody>
</table>

### Plot

![](img_VF.jpg)