## Heating

### Data

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Temperature in Degrees Celcius</th>
      <th>Capacitance in pF</th>
      <th>Dielectric Constant</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>30</td>
      <td>314</td>
      <td>899.71</td>
    </tr>
    <tr>
      <th>1</th>
      <td>35</td>
      <td>318</td>
      <td>911.17</td>
    </tr>
    <tr>
      <th>2</th>
      <td>40</td>
      <td>319</td>
      <td>914.04</td>
    </tr>
    <tr>
      <th>3</th>
      <td>45</td>
      <td>322</td>
      <td>922.64</td>
    </tr>
    <tr>
      <th>4</th>
      <td>50</td>
      <td>323</td>
      <td>925.50</td>
    </tr>
    <tr>
      <th>5</th>
      <td>55</td>
      <td>324</td>
      <td>928.37</td>
    </tr>
    <tr>
      <th>6</th>
      <td>60</td>
      <td>326</td>
      <td>934.10</td>
    </tr>
    <tr>
      <th>7</th>
      <td>65</td>
      <td>329</td>
      <td>942.69</td>
    </tr>
    <tr>
      <th>8</th>
      <td>70</td>
      <td>333</td>
      <td>954.15</td>
    </tr>
    <tr>
      <th>9</th>
      <td>75</td>
      <td>337</td>
      <td>965.62</td>
    </tr>
    <tr>
      <th>10</th>
      <td>80</td>
      <td>342</td>
      <td>979.94</td>
    </tr>
    <tr>
      <th>11</th>
      <td>85</td>
      <td>348</td>
      <td>997.13</td>
    </tr>
    <tr>
      <th>12</th>
      <td>90</td>
      <td>355</td>
      <td>1017.19</td>
    </tr>
    <tr>
      <th>13</th>
      <td>95</td>
      <td>365</td>
      <td>1045.85</td>
    </tr>
    <tr>
      <th>14</th>
      <td>100</td>
      <td>375</td>
      <td>1074.50</td>
    </tr>
    <tr>
      <th>15</th>
      <td>105</td>
      <td>388</td>
      <td>1111.75</td>
    </tr>
    <tr>
      <th>16</th>
      <td>110</td>
      <td>402</td>
      <td>1151.86</td>
    </tr>
    <tr>
      <th>17</th>
      <td>115</td>
      <td>418</td>
      <td>1197.71</td>
    </tr>
    <tr>
      <th>18</th>
      <td>120</td>
      <td>440</td>
      <td>1260.74</td>
    </tr>
    <tr>
      <th>19</th>
      <td>125</td>
      <td>470</td>
      <td>1346.70</td>
    </tr>
    <tr>
      <th>20</th>
      <td>130</td>
      <td>487</td>
      <td>1395.42</td>
    </tr>
    <tr>
      <th>21</th>
      <td>131</td>
      <td>488</td>
      <td>1398.28</td>
    </tr>
    <tr>
      <th>22</th>
      <td>132</td>
      <td>487</td>
      <td>1395.42</td>
    </tr>
    <tr>
      <th>23</th>
      <td>133</td>
      <td>484</td>
      <td>1386.82</td>
    </tr>
    <tr>
      <th>24</th>
      <td>134</td>
      <td>481</td>
      <td>1378.22</td>
    </tr>
    <tr>
      <th>25</th>
      <td>135</td>
      <td>476</td>
      <td>1363.90</td>
    </tr>
    <tr>
      <th>26</th>
      <td>136</td>
      <td>472</td>
      <td>1352.44</td>
    </tr>
    <tr>
      <th>27</th>
      <td>137</td>
      <td>467</td>
      <td>1338.11</td>
    </tr>
    <tr>
      <th>28</th>
      <td>138</td>
      <td>461</td>
      <td>1320.92</td>
    </tr>
    <tr>
      <th>29</th>
      <td>139</td>
      <td>456</td>
      <td>1306.59</td>
    </tr>
    <tr>
      <th>30</th>
      <td>140</td>
      <td>451</td>
      <td>1292.26</td>
    </tr>
    <tr>
      <th>31</th>
      <td>145</td>
      <td>425</td>
      <td>1217.77</td>
    </tr>
    <tr>
      <th>32</th>
      <td>150</td>
      <td>407</td>
      <td>1166.19</td>
    </tr>
    <tr>
      <th>33</th>
      <td>155</td>
      <td>390</td>
      <td>1117.48</td>
    </tr>
    <tr>
      <th>34</th>
      <td>160</td>
      <td>365</td>
      <td>1045.85</td>
    </tr>
    <tr>
      <th>35</th>
      <td>165</td>
      <td>345</td>
      <td>988.54</td>
    </tr>
    <tr>
      <th>36</th>
      <td>170</td>
      <td>327</td>
      <td>936.96</td>
    </tr>
    <tr>
      <th>37</th>
      <td>175</td>
      <td>312</td>
      <td>893.98</td>
    </tr>
    <tr>
      <th>38</th>
      <td>180</td>
      <td>298</td>
      <td>853.87</td>
    </tr>
    <tr>
      <th>39</th>
      <td>185</td>
      <td>287</td>
      <td>822.35</td>
    </tr>
  </tbody>
</table>

### Plot

![](DC1I.jpg)

## Cooling

### Data

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Temperature in Degrees Celcius</th>
      <th>Capacitance in pF</th>
      <th>Dielectric Constant</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>30</td>
      <td>314</td>
      <td>899.71</td>
    </tr>
    <tr>
      <th>1</th>
      <td>35</td>
      <td>318</td>
      <td>911.17</td>
    </tr>
    <tr>
      <th>2</th>
      <td>40</td>
      <td>319</td>
      <td>914.04</td>
    </tr>
    <tr>
      <th>3</th>
      <td>45</td>
      <td>322</td>
      <td>922.64</td>
    </tr>
    <tr>
      <th>4</th>
      <td>50</td>
      <td>323</td>
      <td>925.50</td>
    </tr>
    <tr>
      <th>5</th>
      <td>55</td>
      <td>324</td>
      <td>928.37</td>
    </tr>
    <tr>
      <th>6</th>
      <td>60</td>
      <td>326</td>
      <td>934.10</td>
    </tr>
    <tr>
      <th>7</th>
      <td>65</td>
      <td>329</td>
      <td>942.69</td>
    </tr>
    <tr>
      <th>8</th>
      <td>70</td>
      <td>333</td>
      <td>954.15</td>
    </tr>
    <tr>
      <th>9</th>
      <td>75</td>
      <td>337</td>
      <td>965.62</td>
    </tr>
    <tr>
      <th>10</th>
      <td>80</td>
      <td>342</td>
      <td>979.94</td>
    </tr>
    <tr>
      <th>11</th>
      <td>85</td>
      <td>348</td>
      <td>997.13</td>
    </tr>
    <tr>
      <th>12</th>
      <td>90</td>
      <td>355</td>
      <td>1017.19</td>
    </tr>
    <tr>
      <th>13</th>
      <td>95</td>
      <td>365</td>
      <td>1045.85</td>
    </tr>
    <tr>
      <th>14</th>
      <td>100</td>
      <td>375</td>
      <td>1074.50</td>
    </tr>
    <tr>
      <th>15</th>
      <td>105</td>
      <td>388</td>
      <td>1111.75</td>
    </tr>
    <tr>
      <th>16</th>
      <td>110</td>
      <td>402</td>
      <td>1151.86</td>
    </tr>
    <tr>
      <th>17</th>
      <td>115</td>
      <td>418</td>
      <td>1197.71</td>
    </tr>
    <tr>
      <th>18</th>
      <td>120</td>
      <td>440</td>
      <td>1260.74</td>
    </tr>
    <tr>
      <th>19</th>
      <td>125</td>
      <td>470</td>
      <td>1346.70</td>
    </tr>
    <tr>
      <th>20</th>
      <td>130</td>
      <td>487</td>
      <td>1395.42</td>
    </tr>
    <tr>
      <th>21</th>
      <td>131</td>
      <td>488</td>
      <td>1398.28</td>
    </tr>
    <tr>
      <th>22</th>
      <td>132</td>
      <td>487</td>
      <td>1395.42</td>
    </tr>
    <tr>
      <th>23</th>
      <td>133</td>
      <td>484</td>
      <td>1386.82</td>
    </tr>
    <tr>
      <th>24</th>
      <td>134</td>
      <td>481</td>
      <td>1378.22</td>
    </tr>
    <tr>
      <th>25</th>
      <td>135</td>
      <td>476</td>
      <td>1363.90</td>
    </tr>
    <tr>
      <th>26</th>
      <td>136</td>
      <td>472</td>
      <td>1352.44</td>
    </tr>
    <tr>
      <th>27</th>
      <td>137</td>
      <td>467</td>
      <td>1338.11</td>
    </tr>
    <tr>
      <th>28</th>
      <td>138</td>
      <td>461</td>
      <td>1320.92</td>
    </tr>
    <tr>
      <th>29</th>
      <td>139</td>
      <td>456</td>
      <td>1306.59</td>
    </tr>
    <tr>
      <th>30</th>
      <td>140</td>
      <td>451</td>
      <td>1292.26</td>
    </tr>
    <tr>
      <th>31</th>
      <td>145</td>
      <td>425</td>
      <td>1217.77</td>
    </tr>
    <tr>
      <th>32</th>
      <td>150</td>
      <td>407</td>
      <td>1166.19</td>
    </tr>
    <tr>
      <th>33</th>
      <td>155</td>
      <td>390</td>
      <td>1117.48</td>
    </tr>
    <tr>
      <th>34</th>
      <td>160</td>
      <td>365</td>
      <td>1045.85</td>
    </tr>
    <tr>
      <th>35</th>
      <td>165</td>
      <td>345</td>
      <td>988.54</td>
    </tr>
    <tr>
      <th>36</th>
      <td>170</td>
      <td>327</td>
      <td>936.96</td>
    </tr>
    <tr>
      <th>37</th>
      <td>175</td>
      <td>312</td>
      <td>893.98</td>
    </tr>
    <tr>
      <th>38</th>
      <td>180</td>
      <td>298</td>
      <td>853.87</td>
    </tr>
    <tr>
      <th>39</th>
      <td>185</td>
      <td>287</td>
      <td>822.35</td>
    </tr>
  </tbody>
</table>

### Plot

![](DC2I.jpg)